### ISSUE TITLE
Restart NGINX unit after modules (or something else) changed

### ISSUE THREAD

**Issue by arusakov** [nginxinc/ansible-role-nginx-unit#71]
When you redeploy NGINX unit with different or additional modules, NGINX unit does not restarted and can not see available modules

### Steps to reproduce the behavior:
1. Deploy NGINX Unit role without modules
2. Redeploy NGINX Unit role with unit-python3.8 (for example)
3. When you try to create python application NGINX Unit can not, because module for python is not availible

### Expected behavior
When modules changed NGINX Unit need to be restarted.

### Environment:
-   NGINX Unit role v0.2.2
-   ansible v4.8.0
-   Ubuntu 20.04

**Comment by alessfg** [comment]
This role needs some TLC so extra thanks for taking the time to address and fix this issue!
